# 環境依存しないフレームワークの設定値

spring:
  application:
    name: atrs
  session:
    store-type: redis

# codelist
cron:
  codelist:
    refreshTime: 0 1 0 * * *

# AWS common
cloud:
  aws:
    credentials:
      accesskey: ${aws.access.key.id}
      secretkey: ${aws.secret.access.key}
    stack:
      auto: false
    # CloudWatch
    cloudwatch:
      namespace: ${spring.profiles.active:local}

# actuator
management:
  context-path: /management
  security:
    enabled: false
  health:
    dynamodb:
      enabled: true
