# for development environment on local PC

cloud:
  aws:
    # AWS common
    region:
      static: ap-northeast-1
      auto: false
    credentials:
      instanceProfile: false
    # DynamoDB
    dynamodb:
      # DynamoDBは同一テーブル名を使用しているため、環境毎にエンドポイント、もしくはAWSアカウントを切り替える。
      endpoint: https://dynamodb.ap-northeast-1.amazonaws.com
    # SQS
    sqs:
      region: ap-northeast-1
    # CloudWatch
    cloudwatch:
      region: ${cloud.aws.region.static}

# RDB(RDSを使用)
database:
  common:
    data-source:
      # 各DBの共通設定
      driverClassName: org.postgresql.Driver
      maxActive: 96
      maxIdle: 16
      minIdle: 16
      initialSize: 16
      maxWait: 90000
      password: atrsuser
      username: atrsuser
      validationQuery: SELECT 1
      testOnConnect: true
      testWhileIdle: true
      # Amazon failover の最大値
      # 参考 [http://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html]
      timeBetweenEvictionRunsMillis: 120000
      removeAbandoned: true
      removeAbandonedTimeout: 60
  default:
    schema:
      name: default
  data-sources:
    - schema: default
      url: jdbc:postgresql://atrs-dev-shard.XXXX.ap-northeast-1.rds.amazonaws.com:5432/atrs?socketTimeout=120&connectTimeout=120
    - schema: atrs1
      url: jdbc:postgresql://atrs-dev-shard1.XXXX.ap-northeast-1.rds.amazonaws.com:5432/atrs?socketTimeout=120&connectTimeout=120
    - schema: atrs2
      url: jdbc:postgresql://atrs-dev-shard2.XXXX.ap-northeast-1.rds.amazonaws.com:5432/atrs?socketTimeout=120&connectTimeout=120

# upload directories
upload:
  bucketName: XXXX.YYYY.ZZZZ
  temporaryDirectory: tmp/
  saveDirectory: save/

# SQS queue name
reservation:
  notification:
    # 環境毎にキューを切り替える。
    queue: RESERVATION_NOTICE

# static contents(CloudFrontを利用)
content:
  url: https://XXX.cloudfront.net

# Logging
logging:
  path: /var/log/atrslogs
  # Workaround for duplicated log files
  config: classpath:atrs-logback-spring.xml

# Redis(ローカルPC上のRedis単一ノードを使用、デフォルト設定利用のため設定省略、RedisMessageListenerContainerのconcurrencyLimitのみ設定)
spring:
  redis:
    listener:
      concurrencyLimit: 2
